### ISSUE TITLE
the print button not work

### ISSUE THREAD

**Issue by rcbcodes** [anbcodes/webshop#3]
The print button does **NOTHING**

**Comment by anbcodes** [comment]
Ok, I will start working on this.

**Comment by anbcodes** [comment]
I just was checking this on my computer and it seems to be working fine. So I am not sure how to fix this. You are on OSX, right?

**Comment by anbcodes** [comment]
Hopefully my commit fixes this. It appears that chrome 78 changed how `window.print()` behaves.
